### ISSUE TITLE
Katy Review

### ISSUE THREAD

**Issue by gwenchee** [arfc/2019-ddca-journal-article#18]
This issue can be closed when @katyhuff reviews this version of the DDCA journal article. This version has been reviewed using the writing checklist, edited for comments made in #4 and #16.  

[2019-ddca.pdf](https://github.com/arfc/2019-ddca-journal-article/files/3817923/2019-ddca.pdf)

The most major change is updating the plot with a lot of crosses that compared prediction methods to a bunch of histograms. Plot here: 

![eg01-23-histogram](https://user-images.githubusercontent.com/29397884/68232643-2a022500-ffc3-11e9-855f-90cc4f2679a5.png)

**Comment by katyhuff** [comment]
I have attached full comments on the version from >11 days ago -- it's the pdf associated with #11 .
[2019-ddca-2.pdf](https://github.com/arfc/2019-ddca-journal-article/files/3854742/2019-ddca-2.pdf)


Regarding the plots, this is an improvement ! But, the following comments may improve it further:
- Rather than "time bins" for the x-axis, please be more descriptive and include a unit, and time bounds on each edge of the bins in the histogram.
- The bins should be equal (they should probably all be 50 months long). I recoginize this makes the diagram sparse, but that is the nature of the data. To communicate that the undersupply is not sparse miscommunicates the reality. Allow the plot to be sparse. 
- To add information to this visualization, maybe it would be helpful to add a side panel on the right that integrates over the whole time, but has commodity as its independent variable? Kindof like this:

![image](https://user-images.githubusercontent.com/393899/68999619-daf4a380-0890-11ea-8c75-276056f90753.png)

**Comment by katyhuff** [comment]
Would you like me to review the pdf associated with this issue, or would you like to address the comments in the pdf I have attached above first?

**Comment by gwenchee** [comment]
I will address the comments in the pdf you attached and make a new issue with a PDF for you to review.
